questions = {"results": [{"category": "Mythology", "type": "multiple", "difficulty": "hard",
                          "question": "According to Algonquian folklore, how does one transform into a Wendigo?",
                          "correct_answer": "Participating in cannibalism.",
                          "incorrect_answers": ["Excessive mutilation of animal corpses.",
                                                "Performing a ritual involving murder.",
                                                "Drinking the blood of many slain animals."]},
                         {"category": "Sports", "type": "multiple", "difficulty": "medium",
                          "question": "Which German sportswear company&#039;s logo is the &#039;Formstripe&#039;?",
                          "correct_answer": "Puma",
                          "incorrect_answers": ["Nike", "Adidas", "Reebok"]},
                         {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
                          "question": "Which element has the chemical symbol &#039;Fe&#039;?",
                          "correct_answer": "Iron", "incorrect_answers": ["Gold", "Silver", "Tin"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "easy",
                          "question": "Who had a 1983 hit with the song &#039;Africa&#039;?",
                          "correct_answer": "Toto",
                          "incorrect_answers": ["Foreigner", "Steely Dan", "Journey"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "easy",
                          "question": "Which game did NOT get financed via Crowdfunding?",
                          "correct_answer": "Enter the Gungeon",
                          "incorrect_answers": ["Town of Salem", "Undertale", "Tower Unite"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "easy",
                          "question": "Which country does the band Rammstein hail from?",
                          "correct_answer": "Germany",
                          "incorrect_answers": ["Austria", "Armenia", "Belgium"]},
                         {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                          "difficulty": "easy",
                          "question": "Which anime heavily features music from the genre &quot;Eurobeat&quot;?",
                          "correct_answer": "Initial D",
                          "incorrect_answers": ["Wangan Midnight", "Kino no Tabi", "Cowboy Bebop"]},
                         {"category": "Entertainment: Books", "type": "multiple",
                          "difficulty": "medium",
                          "question": "By what name was the author Eric Blair better known?",
                          "correct_answer": "George Orwell",
                          "incorrect_answers": ["Aldous Huxley", "Ernest Hemingway",
                                                "Ray Bradbury"]},
                         {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                          "question": "Which of the following is NOT a Russian car manufacturer?",
                          "correct_answer": "BYD",
                          "incorrect_answers": ["Silant", "Dragon", "GAZ"]},
                         {"category": "History", "type": "multiple", "difficulty": "medium",
                          "question": "One of the deadliest pandemics, the &quot;Spanish Flu&quot;, killed off what percentage of the human world population at the time?",
                          "correct_answer": "3 to 6 percent",
                          "incorrect_answers": ["6 to 10 percent", "1 to 3 percent",
                                                "less than 1 percent"]},
                         {"category": "Vehicles", "type": "multiple", "difficulty": "medium",
                          "question": "Which of the following car models has been badge-engineered (rebadged) the most?",
                          "correct_answer": "Isuzu Trooper",
                          "incorrect_answers": ["Holden Monaro", "Suzuki Swift", "Chevy Camaro"]},
                         {"category": "Sports", "type": "multiple", "difficulty": "medium",
                          "question": "What is the highest belt you can get in Taekwondo?",
                          "correct_answer": "Black",
                          "incorrect_answers": ["White", "Red", "Green"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "hard",
                          "question": "Who won the 1989 Drum Corps International championships?",
                          "correct_answer": "Santa Clara Vanguard",
                          "incorrect_answers": ["Blue Devils", "The Academy", "The Bluecoats"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "hard",
                          "question": "Which band is the longest active band in the world with no breaks or line-up changes?",
                          "correct_answer": "U2",
                          "incorrect_answers": ["Radiohead", "Rush", "Rolling Stones"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "medium",
                          "question": "Which of these is the name of an American psychedelic rock band formed in 2002 by Benjamin Goldwasser and Andrew VanWyngarden?",
                          "correct_answer": "MGMT",
                          "incorrect_answers": ["MSTRKRFT", "STRFKR", "SBTRKT"]},
                         {"category": "Science & Nature", "type": "multiple",
                          "difficulty": "medium",
                          "question": "What is the atomic number of the element Strontium?",
                          "correct_answer": "38", "incorrect_answers": ["73", "47", "11"]},
                         {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
                          "question": "What is the romanized Arabic word for &quot;moon&quot;?",
                          "correct_answer": "Qamar",
                          "incorrect_answers": ["Najma", "Kawkab", "Shams"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "medium",
                          "question": "In Left 4 Dead, what is the name of the virus, as designated by CEDA, that causes most humans to turn into the Infected?",
                          "correct_answer": "Green Flu",
                          "incorrect_answers": ["Yellow Fever", "T-Virus", "Raspberry Sniffles"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "hard",
                          "question": "How long was the World Record Speed Run of Valve Software&#039;s &quot;Half-Life&quot; that was done in 2014.",
                          "correct_answer": "20 Minutes, 41 Seconds",
                          "incorrect_answers": ["45 Minutes, 32 Seconds", "5 Minutes, 50 Seconds",
                                                "12 Minutes, 59 Seconds"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "hard",
                          "question": "In the game Danganronpa: Happy Trigger Havoc, the character Aoi Asahina&#039;s ultimate ability is what?",
                          "correct_answer": "Ultimate Swimmer",
                          "incorrect_answers": ["Ultimate Detective", "Ultimate Gambler",
                                                "Ultimate Dancer"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "easy",
                          "question": "What collaborative album was released by Kanye West and Jay-Z in 2011?",
                          "correct_answer": "Watch the Throne",
                          "incorrect_answers": ["Distant Relatives", "What a Time to be Alive",
                                                "Unfinished Business"]},
                         {"category": "Geography", "type": "multiple", "difficulty": "hard",
                          "question": "What city is known as the Rose Capital of the World?",
                          "correct_answer": "Tyler, Texas",
                          "incorrect_answers": ["San Diego, California", "Miami, Florida",
                                                "Anaheim, California"]},
                         {"category": "Celebrities", "type": "multiple", "difficulty": "easy",
                          "question": "Aubrey Graham is better known as", "correct_answer": "Drake",
                          "incorrect_answers": ["Travis Scott", "Lil Wayne", "2 Chainz"]},
                         {"category": "Geography", "type": "multiple", "difficulty": "easy",
                          "question": "Which country is the home of the largest Japanese population outside of Japan?",
                          "correct_answer": "Brazil",
                          "incorrect_answers": ["China", "Russia", "The United States"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "medium",
                          "question": "Which of these characters was almost added into Super Smash Bros. Melee, but not included as the game was too far in development?",
                          "correct_answer": "Solid Snake",
                          "incorrect_answers": ["Pit", "Meta Knight", "R.O.B."]},
                         {"category": "Geography", "type": "multiple", "difficulty": "medium",
                          "question": "Which Canadian province has Charlottetown as its capital?",
                          "correct_answer": "Prince Edward Island",
                          "incorrect_answers": ["Saskachewan", "Northwest Terrirories", "Ontario"]},
                         {"category": "History", "type": "multiple", "difficulty": "easy",
                          "question": "How was Socrates executed?", "correct_answer": "Poison",
                          "incorrect_answers": ["Decapitation", "Firing squad", "Crucifixion "]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "easy",
                          "question": "Who was featured in the song &quot;Words&quot; by Feint? ",
                          "correct_answer": "Laura Brehm",
                          "incorrect_answers": ["Anna Yvette ", "Danyka Nadeau", "Veela"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "hard",
                          "question": "Which day in &quot;Papers, Please&quot; does the man in red appear?",
                          "correct_answer": "Day 23",
                          "incorrect_answers": ["Day 20", "Day 17", "Day 15"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "medium",
                          "question": "In the Pok&eacute;mon series, which type is Sudowoodo, the Imitation Pok&eacute;mon?",
                          "correct_answer": "Rock",
                          "incorrect_answers": ["Grass", "Bug", "Ground"]},
                         {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                          "difficulty": "easy",
                          "question": "In the 2012 animated film &quot;Wolf Children&quot;, what are the names of the wolf children?",
                          "correct_answer": "Ame &amp; Yuki",
                          "incorrect_answers": ["Hana &amp; Yuki", "Ame &amp; Hana",
                                                "Chuck &amp; Anna"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "medium",
                          "question": "How many copies have Metallica album &quot;Metallica&quot; (A.K.A The Black Album) sold worldwide (in Millions of Copies)?",
                          "correct_answer": "20.5", "incorrect_answers": ["19.5", "22.5", "25.5"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "medium",
                          "question": "In the game Pok&eacute;mon Conquest, which warlord is able to bond with Zekrom and a shiny Rayquazza?",
                          "correct_answer": "Nobunaga",
                          "incorrect_answers": ["The Player", "Oichi", "Hideyoshi"]},
                         {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                          "difficulty": "medium",
                          "question": "What year did &quot;Bishoujo Senshi Sailor Moon&quot; air in Japan?",
                          "correct_answer": "1992", "incorrect_answers": ["1989", "1990", "1994"]},
                         {"category": "Entertainment: Film", "type": "multiple",
                          "difficulty": "hard",
                          "question": "According to &quot;Star Wars&quot; lore, which planet does Obi-Wan Kenobi come from?",
                          "correct_answer": "Stewjon",
                          "incorrect_answers": ["Alderaan", "Tatooine", "Naboo"]},
                         {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                          "difficulty": "easy",
                          "question": "In &quot;To Love-Ru&quot;, Ren and Run are from what planet?",
                          "correct_answer": "Memorze",
                          "incorrect_answers": ["Deviluke", "Mistletoe", "Okiwana"]},
                         {"category": "Entertainment: Film", "type": "multiple",
                          "difficulty": "medium",
                          "question": "In &quot;Jurassic World&quot;, which company purchases InGen and creates Jurassic World?",
                          "correct_answer": "Masrani Global Corporation ",
                          "incorrect_answers": ["Biology Synthetics Technologies",
                                                "International Genetics Incorporated",
                                                "International Genetic Technologies"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "medium",
                          "question": "What is the name of Joel&#039;s daughter in the game, &quot;The Last of Us&quot;? ",
                          "correct_answer": "Sarah",
                          "incorrect_answers": ["Ellie", "Tess", "Marlene"]},
                         {"category": "Science & Nature", "type": "multiple",
                          "difficulty": "medium",
                          "question": "Which planet did the &quot;Viking 1&quot; spacecraft send surface images of, starting in 1976?",
                          "correct_answer": "Mars",
                          "incorrect_answers": ["Saturn", "Jupiter", "Venus"]},
                         {"category": "Entertainment: Television", "type": "multiple",
                          "difficulty": "medium",
                          "question": "Cesar Romero played which iconic Batman villain from the 1960&#039;s TV show?",
                          "correct_answer": "The Joker",
                          "incorrect_answers": ["The Penguin", "The Riddler", "Mr. Freeze"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "easy",
                          "question": "Who was &quot;Kung Fu Fighting&quot; in 1974?",
                          "correct_answer": "Carl Douglas",
                          "incorrect_answers": ["The Bee Gees", "Heatwave", "Kool &amp; the Gang"]},
                         {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
                          "difficulty": "easy",
                          "question": "Which Pok&eacute;mon and it&#039;s evolutions were banned from appearing in a main role after the Episode 38 Incident?",
                          "correct_answer": "The Porygon Line",
                          "incorrect_answers": ["The Pikachu Line", "The Elekid Line",
                                                "The Magby Line"]},
                         {"category": "History", "type": "multiple", "difficulty": "easy",
                          "question": "On what street did the 1666 Great Fire of London start?",
                          "correct_answer": "Pudding Lane",
                          "incorrect_answers": ["Baker Street", "Houses of Parliament",
                                                "St Paul&#039;s Cathedral"]},
                         {"category": "Entertainment: Music", "type": "multiple",
                          "difficulty": "medium",
                          "question": "What country did Shirley Bassey originate from?",
                          "correct_answer": "Wales",
                          "incorrect_answers": ["America", "England", "Canada"]},
                         {"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
                          "question": "What physics principle relates the net electric flux out of a closed surface to the charge enclosed by that surface?",
                          "correct_answer": "Gauss&#039;s Law",
                          "incorrect_answers": ["Faraday&#039;s Law", "Ampere&#039;s Law",
                                                "Biot-Savart Law"]},
                         {"category": "Politics", "type": "multiple", "difficulty": "medium",
                          "question": "What year did Gerald Ford Become President?",
                          "correct_answer": "1974",
                          "incorrect_answers": ["1977", "1973", "1969"]},
                         {"category": "Sports", "type": "multiple", "difficulty": "easy",
                          "question": "Who did Steven Gerrard win the Champions League with?",
                          "correct_answer": "Liverpool",
                          "incorrect_answers": ["Real Madrid", "Chelsea", "Man City"]},
                         {"category": "History", "type": "multiple", "difficulty": "medium",
                          "question": "In what year did Texas secede from Mexico?",
                          "correct_answer": "1836",
                          "incorrect_answers": ["1838", "1845", "1844"]},
                         {"category": "Science: Mathematics", "type": "multiple",
                          "difficulty": "hard",
                          "question": "The notion of a &quot;set that contains all sets which do not contain themselves&quot; is a paradoxical idea attributed to which English philospher?",
                          "correct_answer": "Bertrand Russel",
                          "incorrect_answers": ["Francis Bacon", "John Locke",
                                                "Alfred North Whitehead"]},
                         {"category": "Entertainment: Video Games", "type": "multiple",
                          "difficulty": "medium",
                          "question": "How many stars are there to collect in Super Mario 64?",
                          "correct_answer": "120", "incorrect_answers": ["60", "80", "100"]}]}


