# Generated by Django 3.2.7 on 2021-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=600)),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
