# Generated by Django 3.2.7 on 2021-09-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0003_alter_questionoption_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
