# Generated by Django 3.2.7 on 2021-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0004_examquestion_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='correctness',
            field=models.BooleanField(default=False),
        ),
    ]
