# Generated by Django 3.2.9 on 2021-12-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0004_alter_batch_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='exam',
            field=models.ManyToManyField(blank=True, to='create_exam.Exam'),
        ),
    ]
