# Generated by Django 3.2.9 on 2021-12-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0005_alter_batch_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examreport',
            old_name='student_exam_duration',
            new_name='student_exam_duration_remaining',
        ),
        migrations.AlterField(
            model_name='examreport',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='incorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='unattempted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
