# Generated by Django 3.2.7 on 2021-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0006_userresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
            ],
        ),
    ]
