# Generated by Django 3.2.8 on 2022-06-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0007_auto_20211208_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examreport',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='examreport',
            name='incorrect',
        ),
        migrations.RemoveField(
            model_name='examreport',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='examreport',
            name='unattempted',
        ),
    ]
