# Generated by Django 3.2.8 on 2022-06-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0008_auto_20220622_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_exam.batch'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_exam.batch'),
        ),
    ]
