# Generated by Django 3.2.8 on 2022-06-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0009_auto_20220622_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='batch',
        ),
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_exam.batch'),
        ),
    ]
