# Generated by Django 3.2.8 on 2021-11-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0009_remove_userinfo_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fullname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
