# Generated by Django 3.2.8 on 2022-06-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_exam', '0010_auto_20220622_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_exam.batch'),
        ),
    ]
